spring:
 datasource:
   driverClassName: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/hotel_data
   username: postgres
   password: postgres
# server:
#  servlet:
#    context-path: /202311